### ISSUE TITLE
Today is 12/29 and not 12/31 and the bot shows 100%<

### ISSUE THREAD

**Issue by pimentelleo** [RedL0tus/YearProgressBot#2]
That is wrong i'm frustrated

**Comment by RedL0tus** [comment]
As I wrote in the channel description, the bot is using the UTC timezone so it is 12/30 there.

`364/365 ~= 0.9972 = 99.72% ~= 100%`

Which means the bot is behaving as intended.

Surely this is less than ideal but I have no good way to fix it.

**Comment by Rajeev404** [comment]
2020 is tricking us
don't fall for it guys

**Comment by mattvasc** [comment]
> 
> 
> As I wrote in the channel description, the bot is using the UTC timezone so it is 12/30 there.
> 
> `364/365 ~= 0.9972 = 99.72% ~= 100%`
> 
> Which means the bot is behaving as intended.
> 
> Surely this is less than ideal but I have no good way to fix it.

What about just floor the result? Would act as expected then.

**Comment by RedL0tus** [comment]
> > As I wrote in the channel description, the bot is using the UTC timezone so it is 12/30 there.
> > `364/365 ~= 0.9972 = 99.72% ~= 100%`
> > Which means the bot is behaving as intended.
> > Surely this is less than ideal but I have no good way to fix it.
> 
> What about just floor the result? Would act as expected then.

That's a good idea and is actually easier to implement than rounding... I've pushed commit [`df376b9`](https://github.com/RedL0tus/YearProgressBot/commit/df376b9cec8834b2d934184bb250498f7f4b651f) which should fix this issue.

**Comment by RedL0tus** [comment]
The new version has been deployed to the server, it should be fine now.

**Comment by RedL0tus** [comment]
I guess this issue can be closed now?

**Comment by pimentelleo** [comment]
Yes! Closedd
